import { useIsMobile } from '../hooks/useIsMobile'

const styles = {
  label: {
    fontSize: '12px',
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    color: '#555555',
    marginBottom: '40px',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: '16px',
  },
  card: {
    backgroundColor: '#161616',
    borderRadius: '8px',
    padding: '28px',
    textAlign: 'left',
    border: '1px solid #1e1e1e',
    textDecoration: 'none',
    display: 'block',
  },
  cardTitle: {
    fontSize: '16px',
    fontWeight: '500',
    color: '#e8e6e0',
    margin: '0 0 10px',
  },
  cardDesc: {
    fontSize: '14px',
    color: '#888888',
    lineHeight: '1.6',
    margin: '0 0 20px',
  },
  tags: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  tag: {
    fontSize: '11px',
    letterSpacing: '0.06em',
    color: '#a78bfa',
    backgroundColor: 'rgba(167, 139, 250, 0.08)',
    border: '1px solid rgba(167, 139, 250, 0.2)',
    borderRadius: '4px',
    padding: '3px 8px',
  },
}

const projects = [
  {
    title: 'This site',
    description: 'Personal portfolio built with React and Vite. Deployed via GitHub Pages.',
    tags: ['React', 'Vite', 'GitHub Pages'],
    href: null,
  },
  {
    title: 'Spotify dashboard',
    description: 'My top tracks and artists from the Spotify API, with a mood summary generated by Claude based on my listening history.',
    tags: ['React', 'Spotify API', 'Claude API', 'GitHub Actions'],
    href: '/portfolio/spotify',
  },
  {
    title: 'Board game personality quiz',
    description: 'A branching narrative quiz set during a game night. Four choices reveal your MBTI personality type and pair you with one of 16 classic board games.',
    tags: ['React', 'Interactive', 'MBTI', 'Branching Narrative'],
    href: '/portfolio/quiz',
  },
]

export default function Projects() {
  const isMobile = useIsMobile()
  return (
    <section id="projects" style={{ padding: isMobile ? '40px 24px' : '60px 48px', borderTop: '1px solid #1e1e1e' }}>
      <p style={styles.label}>Projects</p>
      <div style={styles.grid}>
        {projects.map((p) => {
          const inner = (
            <>
              <h3 style={styles.cardTitle}>{p.title}</h3>
              <p style={styles.cardDesc}>{p.description}</p>
              <div style={styles.tags}>
                {p.tags.map(t => <span key={t} style={styles.tag}>{t}</span>)}
              </div>
            </>
          )
          return p.href
            ? <a key={p.title} href={p.href} style={styles.card}>{inner}</a>
            : <div key={p.title} style={styles.card}>{inner}</div>
        })}
      </div>
    </section>
  )
}
